version: '2'
services:
  app:
    build: docker_images/php
    ports:
      - 81:80
    volumes:
      - ./:/var/www/html
      - ./docker_images/php/httpd.conf:/etc/apache2/sites-available/000-default.conf
#    command:
#      - ./docker_images/php/onrun.sh
    links:
      - mysql:mysql
    networks:
      - default
  mysql:
    build: docker_images/mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: promise_team
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 82:80
    links:
      - mysql:mysql
    depends_on:
      - mysql

